const SUCCESS = '2000';
const FAIL = '4000';

const USER_EXIST = '2201';
const PHONE_REGISTERED = '2202';
const USERNAME_INVALID = '2203';
const PASSWORD_INVALID = '2204';
const PHONE_INVALID = '2205';

const USER_NOT_EXIST = '2101';
const PASSWORD_WRONG = '2102';

export default {
    SUCCESS,
    FAIL,

    USER_EXIST,
    PHONE_INVALID,
    PHONE_REGISTERED,
    USERNAME_INVALID,
    PASSWORD_INVALID,

    USER_NOT_EXIST,
    PASSWORD_WRONG

}
